on: push
jobs: 
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - run: cat *.py
      - run: pip3 install flake8
      - run: flake8 --version

